function err_L1L2 = optimizeGroupLasso(S,X,tau,cvind,cvholdout,normalize,PermTest,lambda1)
  [tmpr,info] = learn_similarity_encoding(S, X, 'L1L2', ...
                    'tau'            , tau            , ...
                    'lambda1'        , lambda1        , ...
                    'cvind'          , cvind          , ...
                    'cvholdout'      , cvholdout      , ...
                    'normalize'      , normalize      , ...
                    'DEBUG'          , false, ...
                    'PermutationTest', PermTest, ...
                    'SmallFootprint' , false, ...
                    'Verbose' , false, ...
                    'AdlasOpts'      , struct()); %#ok<ASGLU>
  err_L1L2 = mean([tmpr.err1]);
end
